import type { CreditCard } from "@/lib/types";

export const MY_CARDS: CreditCard[] = [
  {
    id: "hdfc-regalia-gold",
    name: "HDFC Regalia Gold",
    issuer: "HDFC Bank",
    network: "Visa Signature / World MC",
    annualFee: "₹1,000 + GST (waived above ₹3L spend)",
    rewardRate: "4 points / ₹150 (up to 10x via SmartBuy)",
    milestoneBenefit: "₹1,500 gift voucher at ₹5L annual spend",
    loungeAccess: "8 domestic visits/year",
  },
  {
    id: "hsbc-travelone",
    name: "HSBC TravelOne",
    issuer: "HSBC",
    network: "Visa Signature",
    annualFee: "₹3,999 + GST",
    rewardRate: "3 points / ₹100 (10x on travel portal bookings)",
    milestoneBenefit: "2,500 bonus points at ₹3L annual spend",
    loungeAccess: "4 domestic + 4 international (Priority Pass)",
  },
  {
    id: "hsbc-live-plus",
    name: "HSBC Live+",
    issuer: "HSBC",
    network: "Visa Signature",
    annualFee: "₹999 + GST (waived above ₹2L spend)",
    rewardRate: "10% cashback on dining, food delivery & telecom (capped ₹1,000/month)",
    milestoneBenefit: "None",
    loungeAccess: "Not included",
  },
  {
    id: "axis-atlas",
    name: "Axis Atlas",
    issuer: "Axis Bank",
    network: "Visa Infinite",
    annualFee: "₹5,000 + GST",
    rewardRate: "2 EDGE Miles / ₹100 (5x on travel categories)",
    milestoneBenefit: "2,500–5,000 bonus miles at tiered annual spend",
    loungeAccess: "Tiered: up to unlimited domestic + international",
  },
  {
    id: "yes-marquee",
    name: "YES Bank Marquee",
    issuer: "YES Bank",
    network: "Visa Infinite (metal)",
    annualFee: "₹9,999 + GST",
    rewardRate: "12 points / ₹200",
    milestoneBenefit: "Marquee membership + brand vouchers at renewal",
    loungeAccess: "Unlimited, domestic + international (Priority Pass)",
  },
];
